Updated with testCase.xml and corpora packages
DILCISBoard/eark-ip-test-corpus pull request #192
Opened 2019-03-18 08:35 UTC by PhillipTommerholt

Updated with testCase.xml, real testCase.xsd (no symlink) and corpora packages

2019-03-26 09:38 UTC, carlwilson commented
Conflicts fixed ready for merging.

2019-03-26 10:52 UTC, carlwilson requested changes
Fix package paths in testCase.xml document

2019-05-06 13:20 UTC, andersbonielsen submitted a review, later dismissed
Value updated.

2021-09-23 10:13 UTC, carlwilson approved these changes

2021-09-23 10:27 UTC, merged