Corpora/csip/metadata/amdSec/csip32
DILCISBoard/eark-ip-test-corpus pull request #199
Opened 2019-03-21 16:16 UTC by andersbonielsen

Ready for review. @carlwilson or @ltaimre can look at the structMap part and @PhillipTommerholt for the amdSec part.

2019-04-15 09:13 UTC, PhillipTommerholt commented on corpora/csip/metadata/amdsec/CSIP32/test-case.xml
> +        <package name="IP_18000_CSIP32_1" isValid="FALSE">
isValid should be TRUE according to the new definition in the schema

2019-04-15 09:18 UTC, PhillipTommerholt commented on corpora/csip/metadata/amdsec/CSIP32/test-case.xml
> +        <package name="IP_18000_CSIP32_2" isValid="FALSE">
isValid should be TRUE according to the new definition in the schema for warnings

2019-04-15 09:20 UTC, PhillipTommerholt commented on corpora/csip/metadata/amdsec/CSIP32/IP_18000_CSIP32_3/METS.xml
> +  OBJID="IP_18000_CSIP17_3" TYPE="Database" csip:CONTENTINFORMATIONTYPE="SIARD2"
wrong OBJID

2019-04-15 09:21 UTC, PhillipTommerholt requested changes
Made some few comments. Also: rename test-case.xml to testCase.xml

2021-02-01 11:06 UTC, PhillipTommerholt submitted a review, later dismissed

2021-09-23 10:26 UTC, carlwilson approved these changes

2021-09-23 10:44 UTC, merged