Merge CSIP1 mets/OBJID testCase.xml to integration
DILCISBoard/eark-ip-test-corpus pull request #219
Opened 2020-05-12 17:28 UTC by koit

To my best knowledge, the testCase.xml is now compliant to CSIP v.2.0.3 and after its approval I can move on to fixing the corpus packages.

2020-05-12 17:40 UTC, koit commented
I now noticed that a lot of corpus package changes from last year were not merged and became part of this pull request. Please ignore these as I haven't updated them yet to CSIP v.2.0.3.

I believe the proper way forward is that you review the testCase.xml, then if it's OK I'll update the corpus packages and request another review, and only then will merge the pull request. Otherwise we would have an inconsistent state in integration branch. I apologise for the mess.

2020-05-13 10:23 UTC, PhillipTommerholt submitted a review, later dismissed

2020-12-10 14:10 UTC, PhillipTommerholt commented
@koit why 2.03 and not 2.04?

2021-09-23 12:50 UTC, carlwilson requested changes

2021-09-23 12:50 UTC, carlwilson commented on corpora/csip/metadata/mets-root/CSIP1/testCase.xml
> +  <id specification="CSIP" version="2.0.3" requirementId="CSIP1" />
Needs to be 2.0.4

2021-09-23 13:31 UTC, carlwilson approved these changes

2021-09-23 13:35 UTC, merged