CSIP6: Create testCase.xml
DILCISBoard/eark-ip-test-corpus pull request #224
Opened 2020-06-02 17:11 UTC by koit

2020-08-05 11:04 UTC, PhillipTommerholt approved these changes
It looks good.
You are talking about making changes to the extension schema changing xsd:string to xsd:anyURI. Could it be an idea to also make the @profile attribute mandatory in that schema? 
 I agree that A2 should have a discussion about requirements if it is a valid profile.

2020-08-05 11:09 UTC, PhillipTommerholt requested changes
new version of CSIP is 2.0.4

2020-08-05 11:09 UTC, PhillipTommerholt commented on corpora/csip/metadata/mets-root/CSIP6/testCase.xml
> +  <id specification="CSIP" version="2.0.3" requirementId="CSIP6"/>
2.0.4 is the latest

2021-09-23 12:55 UTC, koit commented on corpora/csip/metadata/mets-root/CSIP6/testCase.xml
> +  <id specification="CSIP" version="2.0.3" requirementId="CSIP6"/>
Fixed.

2021-09-23 13:03 UTC, carlwilson approved these changes

2021-09-23 13:04 UTC, merged