TEST - CSIP1 test case
DILCISBoard/eark-ip-test-corpus pull request #68
Opened 2019-01-29 18:43 UTC by koit

Please review the testCase.xml for CSIP1 `mets/@OBJID`, issue #65. It is compliant with the updated XML template from PR #59. See also E-ARK-CSIP issue https://github.com/DILCISBoard/E-ARK-CSIP/issues/270.

2019-02-15 08:20 UTC, PhillipTommerholt commented on corpus/mets-xml/mets/OBJID/testCase.xml
> +    <reference requirementId="the-use-of-identifiers" URL="http://earkcsip.dilcis.eu/#the-use-of-identifiers">
I am not sure the ID requirement goes for OBJID. I understand the ID requirement as only for XML-datatype "ID".

2019-02-15 09:45 UTC, PhillipTommerholt requested changes
It is not my understanding that the OBJID should follow the ID xml data type rule.
If I am correct, then the files will have to have several amendments. If I am not correct then it seems fine

2019-03-21 10:31 UTC, carlwilson reviewed
Hi @koit I'm wondering about rule 3. I have a feeling we discussed this and thought that it might be better broken into two rules, one for the main package and the other for representations?

2019-03-25 21:13 UTC, koit commented
> Hi @koit I'm wondering about rule 3. I have a feeling we discussed this and thought that it might be better broken into two rules, one for the main package and the other for representations?

I agree @carlwilson, it is done now.

2019-03-26 10:24 UTC, carlwilson approved these changes

2019-03-26 10:24 UTC, PhillipTommerholt approved these changes

2019-04-09 19:34 UTC, merged